"""Subscription-backed product-execution boundary for Agent Trading Arena.

R1 defines runtime vocabulary and planned module ownership only. Runtime code
may depend on the offline kernel in later deliverables; ``arena_kernel`` must
never depend on this package.
"""

from arena_runtime.audit import (
    AUDIT_EVENT_TYPES,
    AUDIT_SCHEMA_VERSION,
    NORMALIZED_EVENTS_PATH,
    PROVIDER_ARTIFACT_PREFIX,
    REDACTION_MARKER,
    AuditArchive,
    AuditArchiveError,
    AuditEvent,
    ProviderArtifactReference,
    audit_event_to_dict,
    dump_audit_event,
    parse_audit_event,
    redact_provider_bytes,
    validate_audit_environment,
)
from arena_runtime.adapters.fake import FakeRunner, FakeRunnerError, FakeRunnerScript
from arena_runtime.adapters.codex import (
    CODEX_ADAPTER_ID,
    CODEX_DOCUMENTATION_URLS,
    CODEX_PREFLIGHT_FAILURES,
    CODEX_PROVIDER_UNAVAILABLE_CODES,
    CODEX_PROVIDER_ID,
    CODEX_QUOTA_ERROR_CODES,
    CODEX_REFUSAL_CODES,
    CodexAdapter,
    CodexExecutionError,
    CodexOutcomeClassification,
    CodexPreflightCapabilities,
    CodexPreflightError,
    CodexSessionError,
    CodexSessionStore,
    classify_codex_outcome,
)
from arena_runtime.adapters.grok_build import (
    GROK_BUILD_ADAPTER_ID,
    GROK_BUILD_DOCUMENTATION_URLS,
    GROK_BUILD_PREFLIGHT_FAILURES,
    GROK_BUILD_PROVIDER_ID,
    GrokBuildAdapter,
    GrokBuildExecutionError,
    GrokBuildPreflightCapabilities,
    GrokBuildPreflightError,
)
from arena_runtime.isolation import (
    READ_ONLY_AREAS,
    REPLICAS_DIRECTORY,
    WRITABLE_AREAS,
    IsolationError,
    ReplicaLaunch,
    enforce_workspace_permissions,
    prepare_replica_launch,
    resolve_replica_path,
    run_isolated_process,
)
from arena_runtime.module_map import CONCEPT_OWNERS, RUNTIME_MODULES
from arena_runtime.process import (
    DEFAULT_STREAM_LIMIT,
    ProcessFacts,
    ProcessSupervisorError,
    run_process,
)
from arena_runtime.registration import (
    CAPABILITY_NAMES,
    SUBSCRIPTION_AUTHENTICATION,
    RuntimeCapabilities,
    RuntimeRegistration,
    dump_runtime_registration,
    parse_runtime_registration,
    runtime_registration_to_dict,
)
from arena_runtime.runner import (
    RUNNER_CONTRACT_VERSION,
    RUNNER_OUTCOMES,
    PreflightResult,
    Runner,
    RunnerContractError,
    RunnerRequest,
    RunnerResult,
    require_matching_identity,
)
from arena_runtime.vocabulary import STABLE_TERMS

__all__ = [
    "AUDIT_EVENT_TYPES",
    "AUDIT_SCHEMA_VERSION",
    "NORMALIZED_EVENTS_PATH",
    "PROVIDER_ARTIFACT_PREFIX",
    "REDACTION_MARKER",
    "AuditArchive",
    "AuditArchiveError",
    "AuditEvent",
    "CODEX_ADAPTER_ID",
    "CODEX_DOCUMENTATION_URLS",
    "CODEX_PREFLIGHT_FAILURES",
    "CODEX_PROVIDER_UNAVAILABLE_CODES",
    "CODEX_PROVIDER_ID",
    "CODEX_QUOTA_ERROR_CODES",
    "CODEX_REFUSAL_CODES",
    "CAPABILITY_NAMES",
    "CONCEPT_OWNERS",
    "GROK_BUILD_ADAPTER_ID",
    "GROK_BUILD_DOCUMENTATION_URLS",
    "GROK_BUILD_PREFLIGHT_FAILURES",
    "GROK_BUILD_PROVIDER_ID",
    "GrokBuildAdapter",
    "GrokBuildExecutionError",
    "GrokBuildPreflightCapabilities",
    "GrokBuildPreflightError",
    "CodexAdapter",
    "CodexExecutionError",
    "CodexOutcomeClassification",
    "CodexPreflightCapabilities",
    "CodexPreflightError",
    "CodexSessionError",
    "CodexSessionStore",
    "classify_codex_outcome",
    "DEFAULT_STREAM_LIMIT",
    "FakeRunner",
    "FakeRunnerError",
    "FakeRunnerScript",
    "IsolationError",
    "PreflightResult",
    "ProcessFacts",
    "ProcessSupervisorError",
    "ProviderArtifactReference",
    "RUNNER_CONTRACT_VERSION",
    "RUNNER_OUTCOMES",
    "RUNTIME_MODULES",
    "READ_ONLY_AREAS",
    "REPLICAS_DIRECTORY",
    "ReplicaLaunch",
    "RuntimeCapabilities",
    "RuntimeRegistration",
    "Runner",
    "RunnerContractError",
    "RunnerRequest",
    "RunnerResult",
    "STABLE_TERMS",
    "SUBSCRIPTION_AUTHENTICATION",
    "WRITABLE_AREAS",
    "audit_event_to_dict",
    "dump_audit_event",
    "dump_runtime_registration",
    "enforce_workspace_permissions",
    "parse_audit_event",
    "parse_runtime_registration",
    "prepare_replica_launch",
    "redact_provider_bytes",
    "require_matching_identity",
    "resolve_replica_path",
    "runtime_registration_to_dict",
    "run_process",
    "run_isolated_process",
    "validate_audit_environment",
]
